### ISSUE TITLE
[Bug] Trying to click the inventory button crashes the game, mouseClicked event handler

### ISSUE THREAD

**Issue by Not-February** [mickelus/scroll-of-harvests#1]
### Observed behaviour

Clicked the scroll button in my inventory, game crashed.

### Expected behaviour

I'd expect the game to not crash and open the GUI the mod adds.

### Steps to reproduce

1. Join world
2. Open inventory
3. Click scroll button

### Crashlog

https://gist.github.com/Febilian/d88b3b5f0c8f89783b78be319a9b5e1f

### Scroll of Harvests version

1.0.0

### mUtil version

4.2.0

### Forge version

1.18.1 - 39.0.59

### Other mods

They should be listed in the crash report already. I wouldn't be surprised if it's a conflict of some kind.

Mouse Tweaks springs to mind as a possible culprit given the error message.

**Comment by mickelus** [comment]
This is caused by some mod registering a tier which returns null as its repair ingredient, which is supposed to never be null. The "correct" way to solve this would be to figure out which mod that is and ask them to not do that :P, but fixing it in harvests would make it more resilient.

It would still help greatly if I knew which mod is causing this.

**Comment by Not-February** [comment]
After some further testing, I can confirm that Roots Classic causes this issue when it's the only other thing installed alongside Scroll of Harvest.

I believe this is because of the Living tools, which repair on their own and aren't meant to be repaired traditionally and thus wouldn't have a material for it.

**Comment by zezreli** [comment]
i also believe that silent gear is causing it to crash aswell

**Comment by KnightMiner** [comment]
Looks like you are also missing a null check for [`getTag`](https://github.com/mickelus/scroll-of-harvests/blob/main/src/main/java/se/mickelus/harvests/gui/TierGui.java#L87), which forge marked nullable. Pickle Tweaks is an example of a mod using a null tag.
