### ISSUE TITLE
[Bug][1.19] Forge breaking changes

### ISSUE THREAD

**Issue by Baggytrousers27** [mickelus/scroll-of-harvests#2]
### Observed behaviour

Crash with message
java.lang.NoClassDefFoundError: net/minecraftforge/client/event/ScreenEvent$InitScreenEvent$Post

### Expected behaviour

Not that.

### Steps to reproduce

Launch MC with Forge 41.0.94 or above.

### Crashlog

https://gist.github.com/Baggytrousers27/9bfacfe1019a1f96b831feaaf2b716dc

### Scroll of Harvests version

harvests-1.19-2.0.0

### mUtil version

mutil-1.19-5.0.0

### Forge version

1.19 41.0.94

### Other mods

[crashlog](https://github.com/mickelus/scroll-of-harvests/files/9127003/crash-2022-07-17_13.42.41-fml.txt) here

**Comment by mickelus** [comment]
Missed this, sorry! Update to latest forge and you should be good!
edit: and the latest version of the mod :P
